name: Terraform Destroy

on:
  workflow_dispatch:  # This triggers the workflow manually

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: your_aws_region

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Terraform
        run: |
          terraform init -backend-config="backend_config.tfvars"  # Point to the same backend config file used in apply

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
